hard_tabs = true
reorder_imports = true
reorder_imports_in_group = true
reorder_imported_names = true
unstable_features = true
indent_style = "Visual"
condense_wildcard_suffixes = true
fn_args_density = "Compressed"
format_strings = true
match_block_trailing_comma = true
max_width = 100
normalize_comments = true
#report_todo = "Always"
#report_fixme = "Always"
struct_field_align_threshold = 20
trailing_semicolon = false
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
